import * as fs from "node:fs";
import * as path from "node:path";

const API_REFERENCE_DIR = path.resolve(
  "./content/docs/(reference)/api-reference",
);

type SectionMeta = {
  title: string;
  description?: string;
  overview?: string;
  pages?: unknown[];
};

type PageFrontmatter = {
  title?: string;
  description?: string;
};

function readJson(filePath: string): unknown {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function parseFrontmatter(filePath: string): PageFrontmatter {
  const source = fs.readFileSync(filePath, "utf8");
  const match = source.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};

  const frontmatter: PageFrontmatter = {};
  for (const line of match[1]!.split("\n")) {
    const field = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!field) continue;

    const key = field[1]!;
    const value = field[2]!.trim().replace(/^["']|["']$/g, "");
    if (key === "title") frontmatter.title = value;
    if (key === "description") frontmatter.description = value;
  }

  return frontmatter;
}

function isPageSlug(value: unknown): value is string {
  return (
    typeof value === "string" &&
    value !== "index" &&
    !value.startsWith("...") &&
    !value.startsWith("---")
  );
}

function fallbackTitle(slug: string): string {
  return slug
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function card({
  title,
  href,
  description,
}: {
  title: string;
  href: string;
  description: string;
}): string {
  return [
    `  <Card title={${JSON.stringify(title)}} href={${JSON.stringify(href)}}>`,
    `    {${JSON.stringify(description)}}`,
    "  </Card>",
  ].join("\n");
}

function generateOverview(sectionDir: string, section: string): void {
  const metaPath = path.join(sectionDir, "meta.json");
  const meta = readJson(metaPath) as SectionMeta;

  if (!meta.title) {
    throw new Error(`${metaPath} must define title`);
  }
  if (!meta.description) {
    throw new Error(`${metaPath} must define description`);
  }
  if (!meta.overview) {
    throw new Error(`${metaPath} must define overview`);
  }

  const pageSlugs = (meta.pages ?? []).filter(isPageSlug);
  const cards = pageSlugs.map((slug) => {
    const pagePath = path.join(sectionDir, `${slug}.mdx`);
    if (!fs.existsSync(pagePath)) {
      throw new Error(`${metaPath} references missing page: ${slug}.mdx`);
    }

    const frontmatter = parseFrontmatter(pagePath);
    if (!frontmatter.title) {
      throw new Error(`${pagePath} must define title frontmatter`);
    }

    return card({
      title: frontmatter.title ?? fallbackTitle(slug),
      href: `/docs/api-reference/${section}/${slug}`,
      description:
        frontmatter.description ??
        `API reference for ${frontmatter.title ?? fallbackTitle(slug)}.`,
    });
  });

  const indexTitle = /\bAPI\b|\bReference\b/i.test(meta.title)
    ? meta.title
    : `${meta.title} API Reference`;
  const output = [
    "---",
    `title: ${indexTitle}`,
    `description: ${meta.description}`,
    "---",
    "",
    "{/* AUTO-GENERATED by scripts/generate-api-reference-overviews.mts */}",
    "{/* Do not edit manually. */}",
    "",
    meta.overview,
    "",
    "## Pages",
    "",
    "<Cards>",
    ...cards,
    "</Cards>",
    "",
  ].join("\n");

  fs.writeFileSync(path.join(sectionDir, "index.mdx"), output);
}

console.log("Generating API reference overview pages...");

const sections = fs
  .readdirSync(API_REFERENCE_DIR, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

let generated = 0;
for (const section of sections) {
  const sectionDir = path.join(API_REFERENCE_DIR, section);
  const metaPath = path.join(sectionDir, "meta.json");
  if (!fs.existsSync(metaPath)) continue;

  const meta = readJson(metaPath) as SectionMeta;
  if (!meta.pages?.includes("index")) continue;

  generateOverview(sectionDir, section);
  generated += 1;
}

console.log(`Generated ${generated} API reference overview pages`);
